version: '3.8'

services:
  whisper-webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      # 基本配置
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ACCESS_CODE=${ACCESS_CODE}
      
      # 可選配置
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SERVER_PORT=5000
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-10000}
    volumes:
      # 持久化存儲
      - ./data/logs:/app/logs
      - ./data/subtitles:/app/subtitles  
      - ./data/summaries:/app/summaries
      - ./data/downloads:/app/downloads
      - ./data/trash:/app/trash
      - ./config.json:/app/config.json:ro  # 只讀掛載配置檔案
    restart: unless-stopped
    
  # GPU 版本（可選）
  whisper-webapp-gpu:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ACCESS_CODE=${ACCESS_CODE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SERVER_PORT=5000
    volumes:
      - ./data/logs:/app/logs
      - ./data/subtitles:/app/subtitles  
      - ./data/summaries:/app/summaries
      - ./data/downloads:/app/downloads
      - ./data/trash:/app/trash
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu 